//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntServiceStack.Common.Types
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    using AntServiceStack.ProtoBuf;
    using AntServiceStack.ServiceHost;
    using AntServiceStack.Baiji.Specific;
    using System.Linq;
    
    
    /// <summary>
    /// SeverityCodeType - Type declaration to be used by other schema. This code
    /// identifies the severity of an API error. A code indicates whether there is an API-
    /// level error or warning that needs to be communicated to the client.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/common/types/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soa.ctrip.com/common/types/v1", IsNullable=false)]
    [DataContract(Namespace="http://soa.ctrip.com/common/types/v1")]
    [ProtoContract()]
    public enum SeverityCodeType
    {
        
        /// <summary>
        /// (out) The request that triggered the error was not processed
        /// successfully. When a serious framework, validation or service-level error occurs, the error
        /// is returned instead of the business data.
        /// </summary>
        [EnumMember()]
        [ProtoEnum()]
        Error,
        
        /// <summary>
        /// (out) The request was processed successfully, but something occurred
        /// that may affect your application or the user. For example, ctrip service may have
        /// changed a value the user sent in. In this case, ctrip service returns a normal,
        /// successful response and also returns the warning.
        /// </summary>
        [EnumMember()]
        [ProtoEnum()]
        Warning,
    }
}
