//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntServiceStack.Extensions.MobileRequestFilter
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    using AntServiceStack.ProtoBuf;
    using AntServiceStack.ServiceHost;
    using System.Threading;
    using System.Threading.Tasks;
    using AntServiceStack.ServiceClient;
    using AntServiceStack.Common.Types;
    
    
    /// <summary>
    /// 验证Token并获取新的Token请求
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/platform/crm/mobileauthservice/v1")]
    [System.Xml.Serialization.XmlRootAttribute("ValidateAndGetNewTokenRequest", Namespace="http://soa.ctrip.com/platform/crm/mobileauthservice/v1", IsNullable=false)]
    [DataContract(Name="ValidateAndGetNewTokenRequest", Namespace="http://soa.ctrip.com/platform/crm/mobileauthservice/v1")]
    [ProtoContract()]
    public partial class ValidateAndGetNewTokenRequest : IHasMobileRequestHead
    {
        
        private string tokenField;
        
        private MobileRequestHead headField;
        
        /// <summary>
        /// Auth令牌
        /// </summary>
        [DataMember()]
        [ProtoMember(1)]
        public string Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(2)]
        public MobileRequestHead head
        {
            get
            {
                return this.headField;
            }
            set
            {
                this.headField = value;
            }
        }
    }
    
    /// <summary>
    /// 验证Token并获取新的Token响应
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/platform/crm/mobileauthservice/v1")]
    [System.Xml.Serialization.XmlRootAttribute("ValidateAndGetNewTokenResponse", Namespace="http://soa.ctrip.com/platform/crm/mobileauthservice/v1", IsNullable=false)]
    [DataContract(Name="ValidateAndGetNewTokenResponse", Namespace="http://soa.ctrip.com/platform/crm/mobileauthservice/v1")]
    [ProtoContract()]
    public partial class ValidateAndGetNewTokenResponse : IHasResponseStatus
    {
        
        private int returnCodeField;
        
        private string messageField;
        
        private string newTokenField;
        
        private string userIDField;
        
        private string loginTypeField;
        
        private string loginNameField;
        
        private int versionField;
        
        private System.DateTime expirationField;
        
        private ResponseStatusType responseStatusField;
        
        /// <summary>
        /// 返回码：
        /// 0-成功
        /// 1001-Token为空
        /// 2001-Token无效
        /// 9000-内部异常
        /// </summary>
        [DataMember()]
        [ProtoMember(1)]
        public int ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
        
        /// <summary>
        /// 返回消息
        /// </summary>
        [DataMember()]
        [ProtoMember(2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <summary>
        /// 新的Token
        /// </summary>
        [DataMember()]
        [ProtoMember(3)]
        public string NewToken
        {
            get
            {
                return this.newTokenField;
            }
            set
            {
                this.newTokenField = value;
            }
        }
        
        /// <summary>
        /// UserID
        /// </summary>
        [DataMember()]
        [ProtoMember(4)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <summary>
        /// 登录类型
        /// </summary>
        [DataMember()]
        [ProtoMember(5)]
        public string LoginType
        {
            get
            {
                return this.loginTypeField;
            }
            set
            {
                this.loginTypeField = value;
            }
        }
        
        /// <summary>
        /// 登录名
        /// </summary>
        [DataMember()]
        [ProtoMember(6)]
        public string LoginName
        {
            get
            {
                return this.loginNameField;
            }
            set
            {
                this.loginNameField = value;
            }
        }
        
        /// <summary>
        /// AuthenticationVersion对象的版本
        /// </summary>
        [DataMember()]
        [ProtoMember(7)]
        public int Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <summary>
        /// 过期时间
        /// </summary>
        [DataMember()]
        [ProtoMember(8)]
        public System.DateTime Expiration
        {
            get
            {
                return this.expirationField;
            }
            set
            {
                this.expirationField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(9)]
        public ResponseStatusType ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <summary>
    /// 获取新的Token请求
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/platform/crm/mobileauthservice/v1")]
    [System.Xml.Serialization.XmlRootAttribute("GetNewTokenRequest", Namespace="http://soa.ctrip.com/platform/crm/mobileauthservice/v1", IsNullable=false)]
    [DataContract(Name="GetNewTokenRequest", Namespace="http://soa.ctrip.com/platform/crm/mobileauthservice/v1")]
    [ProtoContract()]
    public partial class GetNewTokenRequest
    {
        
        private string loginNameField;
        
        private string passwordField;
        
        private MobileRequestHead headField;
        
        /// <summary>
        /// 登录名，可以为手机号码，Email，UID
        /// </summary>
        [DataMember()]
        [ProtoMember(1)]
        public string LoginName
        {
            get
            {
                return this.loginNameField;
            }
            set
            {
                this.loginNameField = value;
            }
        }
        
        /// <summary>
        /// Password
        /// </summary>
        [DataMember()]
        [ProtoMember(2)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(3)]
        public MobileRequestHead head
        {
            get
            {
                return this.headField;
            }
            set
            {
                this.headField = value;
            }
        }
    }
    
    /// <summary>
    /// 获取新的Token响应
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/platform/crm/mobileauthservice/v1")]
    [System.Xml.Serialization.XmlRootAttribute("GetNewTokenResponse", Namespace="http://soa.ctrip.com/platform/crm/mobileauthservice/v1", IsNullable=false)]
    [DataContract(Name="GetNewTokenResponse", Namespace="http://soa.ctrip.com/platform/crm/mobileauthservice/v1")]
    [ProtoContract()]
    public partial class GetNewTokenResponse
    {
        
        private int returnCodeField;
        
        private string messageField;
        
        private string uIDField;
        
        private string tokenField;
        
        private int versionField;
        
        private System.DateTime expirationField;
        
        private ResponseStatusType responseStatusField;
        
        /// <summary>
        /// 返回码：
        /// 0-成功
        /// 1001-登录名为空
        /// 1002-密码为空
        /// 2001-身份验证失败
        /// 9000-内部异常
        /// </summary>
        [DataMember()]
        [ProtoMember(1)]
        public int ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
        
        /// <summary>
        /// 返回消息
        /// </summary>
        [DataMember()]
        [ProtoMember(2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <summary>
        /// UID
        /// </summary>
        [DataMember()]
        [ProtoMember(3)]
        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
        
        /// <summary>
        /// Token
        /// </summary>
        [DataMember()]
        [ProtoMember(4)]
        public string Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <summary>
        /// AuthenticationVersion对象的版本
        /// </summary>
        [DataMember()]
        [ProtoMember(5)]
        public int Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <summary>
        /// 过期时间
        /// </summary>
        [DataMember()]
        [ProtoMember(6)]
        public System.DateTime Expiration
        {
            get
            {
                return this.expirationField;
            }
            set
            {
                this.expirationField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(7)]
        public ResponseStatusType ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <summary>
    /// Service client auto-generated by SOA tool, DO NOT CHANGE!
    /// 
    /// 
    /// </summary>
    public class MobileAuthServiceClient : ServiceClientBase<MobileAuthServiceClient>
    {
        
        public const string CodeGeneratorVersion = "2.0.7.1";
        
        public const string OriginalServiceName = "MobileAuthService";
        
        public const string OriginalServiceNamespace = "http://soa.ctrip.com/platform/crm/mobileauthservice/v1";
        
        public const string OriginalServiceType = "NonSLB";
        
        private MobileAuthServiceClient(string baseUri) : 
                base(baseUri)
        {
        }
        
        private MobileAuthServiceClient(string serviceName, string serviceNamespace, string subEnv) : 
                base(serviceName, serviceNamespace, subEnv)
        {
        }
        
        public virtual CheckHealthResponseType CheckHealth(CheckHealthRequestType checkHealthIn)
        {
            return base.Invoke<CheckHealthResponseType>("CheckHealth", checkHealthIn);
        }
        
        public virtual Task<CheckHealthResponseType> CreateAsyncTaskOfCheckHealth(CheckHealthRequestType checkHealthIn, CancellationToken? cancellationToken = null, TaskCreationOptions? taskCreationOptions = null)
        {
            return base.CreateAsyncTask<CheckHealthRequestType, CheckHealthResponseType>("CheckHealth", checkHealthIn, cancellationToken, taskCreationOptions);
        }
        
        public virtual Task<CheckHealthResponseType> StartIOCPTaskOfCheckHealth(CheckHealthRequestType checkHealthIn)
        {
            return base.StartIOCPTask<CheckHealthResponseType>("CheckHealth", checkHealthIn);
        }
        
        public virtual ValidateAndGetNewTokenResponse ValidateAndGetNewToken(ValidateAndGetNewTokenRequest validateAndGetNewTokenIn)
        {
            return base.Invoke<ValidateAndGetNewTokenResponse>("ValidateAndGetNewToken", validateAndGetNewTokenIn);
        }
        
        public virtual Task<ValidateAndGetNewTokenResponse> CreateAsyncTaskOfValidateAndGetNewToken(ValidateAndGetNewTokenRequest validateAndGetNewTokenIn, CancellationToken? cancellationToken = null, TaskCreationOptions? taskCreationOptions = null)
        {
            return base.CreateAsyncTask<ValidateAndGetNewTokenRequest, ValidateAndGetNewTokenResponse>("ValidateAndGetNewToken", validateAndGetNewTokenIn, cancellationToken, taskCreationOptions);
        }
        
        public virtual Task<ValidateAndGetNewTokenResponse> StartIOCPTaskOfValidateAndGetNewToken(ValidateAndGetNewTokenRequest validateAndGetNewTokenIn)
        {
            return base.StartIOCPTask<ValidateAndGetNewTokenResponse>("ValidateAndGetNewToken", validateAndGetNewTokenIn);
        }
    }
}
