//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntServiceStack.Common.Types
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    using AntServiceStack.ProtoBuf;
    using AntServiceStack.ServiceHost;
    using AntServiceStack.Baiji.Specific;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace= "http://soa.ant.com/common/types/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace= "http://soa.ant.com/common/types/v1", IsNullable=false)]
    [DataContract(Namespace= "http://soa.ant.com/common/types/v1")]
    [ProtoContract()]
    public enum ErrorClassificationCodeType
    {
        
        /// <summary>
        /// Indicates that an error has occurred in the service implementation, such as business logic error or other backend error.
        /// </summary>
        [EnumMember()]
        [ProtoEnum()]
        ServiceError,
        
        /// <summary>
        /// Indicates that an error has occurred because of framework-level request validation failure.
        /// This is usually because client consumer has attempted to submit invalid data (or missing data)
        /// in the request when making API call.
        /// </summary>
        [EnumMember()]
        [ProtoEnum()]
        ValidationError,

        /// <summary>
        /// Indicates that an error has occurred in the ant soa framework(AntServiceStack), such as a serialization/descrialization failure.
        /// </summary>
        [EnumMember()]
        [ProtoEnum()]
        FrameworkError,

        /// <summary>
        /// Indicates that a ant service is unable to meet a specified service level agreement.
        /// typical cases that will cause this error including: 1) continues high service call latency;
        /// 2) continues high service call error rate, in these cases, to avoid further service deterioration,
        /// the service framework will enter into a self-protecting mode, by tripping the service call circuit
        /// and return SLAError to clients. Later, when the situation improves, the service framework will
        /// close the service call circuit again and continue to serve the clients.
        /// </summary>
        [EnumMember()]
        [ProtoEnum()]
        SLAError,
    }
}
