//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntServiceStack.Common.Types
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    using AntServiceStack.ProtoBuf;
    using AntServiceStack.Baiji.Specific;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ant.com/mobile/common/types/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soa.ant.com/mobile/common/types/v1", IsNullable=true)]
    [DataContract(Namespace="http://soa.ant.com/mobile/common/types/v1")]
    [ProtoContract()]
    public partial class MobileRequestHead : ISpecificRecord
    {
        
        private string syscodeField;
        
        private string langField;
        
        private string authField;
        
        private string cidField;
        
        private string ctokField;
        
        private string cverField;
        
        private string sidField;
        
        private List<ExtensionFieldType> extensionField;
        
        private string pauthField;
        
        private string sauthField;
        
        public static readonly AntServiceStack.Baiji.Schema.Schema SCHEMA = AntServiceStack.Baiji.Schema.Schema.Parse(((("{\"type\":\"record\",\"name\":\"MobileRequestHead\",\"namespace\":\"" + typeof(MobileRequestHead).Namespace) 
                        + (@""",""doc"":null,""fields"":[{""name"":""syscode"",""type"":[""string"",""null""]},{""name"":""lang"",""type"":[""string"",""null""]},{""name"":""auth"",""type"":[""string"",""null""]},{""name"":""cid"",""type"":[""string"",""null""]},{""name"":""ctok"",""type"":[""string"",""null""]},{""name"":""cver"",""type"":[""string"",""null""]},{""name"":""sid"",""type"":[""string"",""null""]},{""name"":""extension"",""type"":[{""type"":""array"",""items"":{""type"":""record"",""name"":""ExtensionFieldType"",""namespace"":""" + typeof(ExtensionFieldType).Namespace)) 
                        + "\",\"doc\":null,\"fields\":[{\"name\":\"name\",\"type\":[\"string\",\"null\"]},{\"name\":\"value\",\"" +
                            "type\":[\"string\",\"null\"]}]}},\"null\"]},{\"name\":\"pauth\",\"type\":[\"string\",\"null\"]},{" +
                            "\"name\":\"sauth\",\"type\":[\"string\",\"null\"]}]}"));
        
        /// <summary>
        /// 平台号
        /// </summary>
        [DataMember()]
        [ProtoMember(1)]
        public string syscode
        {
            get
            {
                return this.syscodeField;
            }
            set
            {
                this.syscodeField = value;
            }
        }
        
        /// <summary>
        /// 语言
        /// </summary>
        [DataMember()]
        [ProtoMember(2)]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
        
        /// <summary>
        /// 认证信息
        /// </summary>
        [DataMember()]
        [ProtoMember(3)]
        public string auth
        {
            get
            {
                return this.authField;
            }
            set
            {
                this.authField = value;
            }
        }
        
        /// <summary>
        /// 设备号
        /// </summary>
        [DataMember()]
        [ProtoMember(4)]
        public string cid
        {
            get
            {
                return this.cidField;
            }
            set
            {
                this.cidField = value;
            }
        }
        
        /// <summary>
        /// 设备号替补
        /// </summary>
        [DataMember()]
        [ProtoMember(5)]
        public string ctok
        {
            get
            {
                return this.ctokField;
            }
            set
            {
                this.ctokField = value;
            }
        }
        
        /// <summary>
        /// 版本号
        /// </summary>
        [DataMember()]
        [ProtoMember(6)]
        public string cver
        {
            get
            {
                return this.cverField;
            }
            set
            {
                this.cverField = value;
            }
        }
        
        /// <summary>
        /// 渠道包里预置的渠道号
        /// </summary>
        [DataMember()]
        [ProtoMember(7)]
        public string sid
        {
            get
            {
                return this.sidField;
            }
            set
            {
                this.sidField = value;
            }
        }
        
        /// <summary>
        /// 用于存放更多的非标准的扩展数据，PD按实际需要使用
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        [DataMember()]
        [ProtoMember(8)]
        public List<ExtensionFieldType> extension
        {
            get
            {
                if ((this.extensionField == null))
                {
                    this.extensionField = new List<ExtensionFieldType>();
                }
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <summary>
        /// 非会员认证信息
        /// </summary>
        [DataMember()]
        [ProtoMember(9)]
        public string pauth
        {
            get
            {
                return this.pauthField;
            }
            set
            {
                this.pauthField = value;
            }
        }
        
        /// <summary>
        /// 二级认证信息
        /// </summary>
        [DataMember()]
        [ProtoMember(10)]
        public string sauth
        {
            get
            {
                return this.sauthField;
            }
            set
            {
                this.sauthField = value;
            }
        }
        
        public virtual AntServiceStack.Baiji.Schema.Schema GetSchema()
        {
            return SCHEMA;
        }
        
        public virtual object Get(int fieldPos)
        {
            switch(fieldPos)
            {
                case 0: return this.syscode;
                case 1: return this.lang;
                case 2: return this.auth;
                case 3: return this.cid;
                case 4: return this.ctok;
                case 5: return this.cver;
                case 6: return this.sid;
                case 7: return this.extension;
                case 8: return this.pauth;
                case 9: return this.sauth;
                default: throw new AntServiceStack.Baiji.Exceptions.BaijiRuntimeException("Bad index " + fieldPos + " in Get()");
            }
        }
        
        public virtual void Put(int fieldPos, object fieldValue)
        {
            switch(fieldPos)
            {
                case 0: this.syscode = (System.String)fieldValue; break;
                case 1: this.lang = (System.String)fieldValue; break;
                case 2: this.auth = (System.String)fieldValue; break;
                case 3: this.cid = (System.String)fieldValue; break;
                case 4: this.ctok = (System.String)fieldValue; break;
                case 5: this.cver = (System.String)fieldValue; break;
                case 6: this.sid = (System.String)fieldValue; break;
                case 7: this.extension = (List<ExtensionFieldType>)fieldValue; break;
                case 8: this.pauth = (System.String)fieldValue; break;
                case 9: this.sauth = (System.String)fieldValue; break;
                default: throw new AntServiceStack.Baiji.Exceptions.BaijiRuntimeException("Bad index " + fieldPos + " in Put()");
            }
        }
        
        public virtual object Get(string fieldName)
        {
            var recordSchema = GetSchema() as AntServiceStack.Baiji.Schema.RecordSchema;
            if (recordSchema == null)
            {
                return null;
            }
            AntServiceStack.Baiji.Schema.Field field;
            if (!recordSchema.TryGetField(fieldName, out field))
            {
                return null;
            }
            return Get(field.Pos);
        }
        
        public virtual void Put(string fieldName, object fieldValue)
        {
            var recordSchema = GetSchema() as AntServiceStack.Baiji.Schema.RecordSchema;
            if (recordSchema == null)
            {
                return ;
            }
            AntServiceStack.Baiji.Schema.Field field;
            if (!recordSchema.TryGetField(fieldName, out field))
            {
                return ;
            }
            Put(field.Pos, fieldValue);
        }
    }
}
